--------------------------------------------------------
--  Fichier créé - dimanche-novembre-27-2022   
--------------------------------------------------------
DROP TABLE "SYSTEM"."ACTUALITE";
DROP TABLE "SYSTEM"."EMPLOYES";
DROP TABLE "SYSTEM"."GESTION_MUSIQUE";
DROP TABLE "SYSTEM"."PODCAST";
DROP TABLE "SYSTEM"."PUB1";
--------------------------------------------------------
--  DDL for Table ACTUALITE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ACTUALITE" 
   (	"IDP" VARCHAR2(20 BYTE), 
	"TITRE" VARCHAR2(20 BYTE), 
	"LIEU" VARCHAR2(50 BYTE), 
	"DATEA" VARCHAR2(20 BYTE), 
	"SOURCE" VARCHAR2(50 BYTE), 
	"CATEGORIE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"IMAGE" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYES" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NUMERO_TELEPHONE" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_MUSIQUE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_MUSIQUE" 
   (	"TITRE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"NATIONALITE" VARCHAR2(20 BYTE), 
	"GENRE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PODCAST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PODCAST" 
   (	"IDPOD" NUMBER, 
	"SUJET" VARCHAR2(20 BYTE), 
	"PARTICIPANT" NUMBER, 
	"SCRIPT" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(20 BYTE), 
	"DATEPOD" VARCHAR2(20 BYTE), 
	"HEURE" VARCHAR2(20 BYTE), 
	"CATEGORIEPOD" VARCHAR2(20 BYTE), 
	"AUDIO" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PUB1
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PUB1" 
   (	"ID" NUMBER, 
	"TITRE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATE_P" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ACTUALITE
SET DEFINE OFF;
Insert into SYSTEM.ACTUALITE (IDP,TITRE,LIEU,DATEA,SOURCE,CATEGORIE,DESCRIPTION,IMAGE) values ('123','premiertest','tunisie','14-AUG-02','wikipedia','categorie sante','ceci est un test','C:/Users/blade/OneDrive/Bureau/2eme esprit/Project C++ groupe 5 smart radio/projects/Gestion_dactualte/images/large (2).png');
Insert into SYSTEM.ACTUALITE (IDP,TITRE,LIEU,DATEA,SOURCE,CATEGORIE,DESCRIPTION,IMAGE) values ('456812','titreajout',null,'01-JAN-00',null,'categorie divers',null,null);
Insert into SYSTEM.ACTUALITE (IDP,TITRE,LIEU,DATEA,SOURCE,CATEGORIE,DESCRIPTION,IMAGE) values ('12345789','tessrt',null,'01-JAN-00',null,'categorie politique',null,'C:/Users/blade/OneDrive/Bureau/logo glasses/fond.png');
Insert into SYSTEM.ACTUALITE (IDP,TITRE,LIEU,DATEA,SOURCE,CATEGORIE,DESCRIPTION,IMAGE) values ('56324','testidl',null,'01-JAN-00',null,'categorie politique',null,null);
Insert into SYSTEM.ACTUALITE (IDP,TITRE,LIEU,DATEA,SOURCE,CATEGORIE,DESCRIPTION,IMAGE) values ('45788965','tresfe',null,'01-JAN-00',null,'categorie politique',null,null);
Insert into SYSTEM.ACTUALITE (IDP,TITRE,LIEU,DATEA,SOURCE,CATEGORIE,DESCRIPTION,IMAGE) values ('786542','testarduino',null,'01-JAN-00',null,'categorie politique',null,null);
Insert into SYSTEM.ACTUALITE (IDP,TITRE,LIEU,DATEA,SOURCE,CATEGORIE,DESCRIPTION,IMAGE) values ('testid123','arduino uno dos',null,'sam. janv. 1 2000',null,'categorie politique',null,null);
Insert into SYSTEM.ACTUALITE (IDP,TITRE,LIEU,DATEA,SOURCE,CATEGORIE,DESCRIPTION,IMAGE) values ('457889','tresfey',null,'01-JAN-00',null,'categorie espace',null,null);
Insert into SYSTEM.ACTUALITE (IDP,TITRE,LIEU,DATEA,SOURCE,CATEGORIE,DESCRIPTION,IMAGE) values ('58586','tezsrintegr','145','04-JAN-04','azeea','categorie technologique','azeaer',null);
REM INSERTING into SYSTEM.EMPLOYES
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_MUSIQUE
SET DEFINE OFF;
REM INSERTING into SYSTEM.PODCAST
SET DEFINE OFF;
REM INSERTING into SYSTEM.PUB1
SET DEFINE OFF;
Insert into SYSTEM.PUB1 (ID,TITRE,DESCRIPTION,TYPE,DATE_P) values (454556,'khaliltest','test12145','Culture','4578');
--------------------------------------------------------
--  DDL for Index ACTUALITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ACTUALITE_PK" ON "SYSTEM"."ACTUALITE" ("IDP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_ACTUALITE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_ACTUALITE" ON "SYSTEM"."ACTUALITE" ("TITRE", "CATEGORIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACTUALITE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ACTUALITE" ADD CONSTRAINT "UK_ACTUALITE" UNIQUE ("TITRE", "CATEGORIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ACTUALITE" ADD CONSTRAINT "ACTUALITE_PK" PRIMARY KEY ("IDP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ACTUALITE" MODIFY ("TITRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACTUALITE" MODIFY ("IDP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PODCAST
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PODCAST" MODIFY ("IDPOD" NOT NULL ENABLE);
